FROM node:18-alpine

WORKDIR /app

# Копируем package.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install --production

# Копируем backend код
COPY server ./server

# Открываем порт
EXPOSE 5000

# Запускаем сервер
CMD ["node", "server/index.js"]

